### ISSUE TITLE
Nagstamon-3.16.0-win64_setup.exe Virus

### ISSUE THREAD

**Issue by Luiso0o** [HenriWahl/Nagstamon#1065]
I check the file with Virus Total and it has a malware:
![image](https://github.com/user-attachments/assets/d5978008-900b-4a31-8c13-9caa7805a031)

**Comment by Luiso0o** [comment]
The same for the other file Nagstamon-3.16.0-win32_setup.exe:

![image](https://github.com/user-attachments/assets/e82dd899-ada2-418b-9f0b-86c77349e624)

**Comment by HenriWahl** [comment]
Hi @Luiso0o - from my side there is no malware included. :-)
This is a false positive, considerung that only 2 of 72 antivirus engines cry. If some big names would also detect more, this should trigger some deeper inspections of the used components. Consider it being 70 of 72 stars...
As a background: the Windows version is packaged with pyinstaller, which since years has the problem that its resulting binaries are flagged as malware.

**Comment by NoobSpielt** [comment]
Update. Windows defender starts flagging and blocking Nagstamon 3.16.1 on my Computer and the Computers of my colleagues

 Windows 10 Enterprise LTSC 21H2 
 
 
 
 weird thing...

**Comment by HenriWahl** [comment]
@NoobSpielt strange as https://www.virustotal.com/gui/file/20907c326c882e651d1ca413f86721b1f2c4dd1999e10ca8bcaf7a6eeecf4ea0 shows it is fully clean.

Do you have an option to report it as false positive?

**Comment by HenriWahl** [comment]
In the mean time the 3.16.2 is out without any positives on virus total.com.
