### ISSUE TITLE
Option to ignore SSL errors

### ISSUE THREAD

**Issue by bemeyert** [HenriWahl/Nagstamon#126]
Hi all,
I can no longer connect to our server because of a SSL verification error. It is a self-signed certificate. So I know that it can't be verified. Please add an option to ignore SSL problems. Currently I can't use nagstamon.

The error:

```
ERROR: 2014-12-19 11:17:55.955827 7val icinga   Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Nagstamon/Server/Generic.py", line 1077, in FetchURL
    urlcontent = self.urlopener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

Thx

**Comment by gerdesj** [comment]
Just to spell out the fix for Gentoo (thanks HW):
Grab a unified diff for the patch mentioned above by appending .patch to the URL in HenriWahl's comment above and save it to eg (choose your filename) /etc/portage/net-analyzer/nagstamon/python2.9.patch

Follow this: http://wiki.gentoo.org/wiki//etc/portage/patches#Adding_support_for_user_patches_to_your_ebuilds to enable epatch_user for all ebuilds because the ebuild for Nagstamon doesn't have direct support for epatch_user.

Re-emerge nagstamon and look for this in the output:
 * Applying user patches from /etc/portage/patches//net-analyzer/nagstamon ...
 *   python-2.9.patch ...                                                                                                                                 
 * Done with patching

Hooray, it's working again.

**Comment by lhost** [comment]
Please, see my pull request with the comment: 
https://github.com/HenriWahl/Nagstamon/pull/134
http://blog.hostname.sk/2015/02/27/nagstamon-python-openssl-certificate-validation/

**Comment by sinaowolabi** [comment]
Any advice for Ubuntu (specifically, 15.04) users?

**Comment by HenriWahl** [comment]
Not yet - either change the files as in https://github.com/HenriWahl/Nagstamon/commit/1f99d2f70db544652d30dca4e718ba733d3fd7cf or stay tuned for the next version.

**Comment by soxwellfb** [comment]
Just a note to say that the 10.10.5 patch for OS X bumped the version of Python from 2.7.6 to 2.7.10, so it's now showing the SSL certificate issue against a self signed Nagios server.

I applied the patch by:
* saving https://github.com/HenriWahl/Nagstamon/commit/1f99d2f70db544652d30dca4e718ba733d3fd7cf.patch to a file (in my case nagstamon-python2.7.9.patch)
* In Terminal:
```
/Applications/Nagstamon.app/Contents/MacOS/Nagstamon-src
patch -p2 <  <path to patch file>/nagstamon-python2.7.9.patch
```
This may be of use to someone.

**Comment by varac** [comment]
@HenriWahl Any change to get a new release out ? Last one (1.0.1) is already over a year now. I would love to have this feature without patching files.

**Comment by HenriWahl** [comment]
You can already check the still alpha but yet usable releases of the new 2.0 version, which is a port to Qt5 instead of GTK2 and thus rather time consuming.
Especially this bug is fixed there due to the use of the Requests module. The Qt5 port additionally comes with native OSX support.
See https://nagstamon.ifw-dresden.de/ for Details.

**Comment by HenriWahl** [comment]
Right now the next alpha is out :-)
