### ISSUE TITLE
Nagstamon Silent Install

### ISSUE THREAD

**Issue by jawalo2k** [HenriWahl/Nagstamon#175]
Hi Team,

Hoping some one can assist. 

We would like to deploy Nagstamon to different department users (Windows PC's) through our internal software deployment system. I have thus far been able to get the software to download and install remotely but we are now looking at ways to make the install process silent (no dialogs). Can the Nagstamon installer natively handle this or would it be best to repack it myself into a new installer?

The second part of the issues in the configuration file. As each department has read access to the devices within their department only what would be the best way to deploy the config file. The Department users will all share a common guest like username and password for their department.

I imagine that I could either:
a) create a deployment script that copies a template configuration file to the relevant install location using windows global variables. 
b) Include the configuration files in the repacked installer option mentioned above

Could some one just confirm where these configuration files are or suggest an alternative method?

Regards,

**Comment by HenriWahl** [comment]
Regarding the silent install: Nagstamon Windows installer is packaged with InnoSetup - maybe there is already a silent install option as default. Otherwise I might look for such an option when packaging the next Nagstamon installer, which will be with the 2.0 beta releases coming soon (I hope).

If you put your desired configuration directory into the Nagstamon binary path (like C:\Program Files\Nagstamon) and name it 'nagstamon.config' this one should be preferred before any other user config - at least it was intended to work like this some years ago.

**Comment by HenriWahl** [comment]
Check the Nagstamon package in http://chocolatey.org - they somehow managed to do a silent install.
