### ISSUE TITLE
v2.0 application can be started twice

### ISSUE THREAD

**Issue by sronline** [HenriWahl/Nagstamon#189]
the application should check if it has already been started

**Comment by HenriWahl** [comment]
Why?

There are users running several instances with different configuration.

**Comment by gtozzi** [comment]
I am also interested on this: there also are users not willing to risk running several instances by mistake: when the session gets saved and restored, it could happen :)

Could this be an option? I could write the code for it using the lockfile (https://pythonhosted.org/lockfile/lockfile.html) module, but the hard part is adding the checkbox to the ui ;)

**Comment by HenriWahl** [comment]
The GUI part is not that hard, I just imagine it somehow confusing if you have one config allowing multiple instances and one not...

**Comment by gtozzi** [comment]
True. But i think then we can say nobody has a reason to run two instances over the same config. Am I wrong?

**Comment by HenriWahl** [comment]
No, you are right. So maybe it is enough to check at start if there is an process with the same command line args?

**Comment by gtozzi** [comment]
I don't think this is doable in a safe and portable way.
But it could place a lock on the config folder using the lockfile module or by creating a pid file inside it. If the lock fails, then there is another instance holding the lock for the same folder.

**Comment by HenriWahl** [comment]
Doesn't this bring even more overhead? Maybe it would be enough to evaluate a --session argument and then check if already some Nagstamon runs? This would only happen on Linux/BSD anyway.

**Comment by gtozzi** [comment]
What do you mean by overhead? Locking a folder or creating a 5-bytes file happens in the blink of an eye.
In my case there is not always a --session argument. It could also happen on Windows, if you have it both on autostart and in the register, by example, or if you start it manually while it is being autostarted on slow machines; i don't know about OSX.

**Comment by HenriWahl** [comment]
Overhead means dependencies, checks and stuff. New error source like Nagstamon-crashed-but-PID-file-still-hanging-around-and-blocking-new-start. But you are right, quite possibly this could happen on other OS too.
I found the psutil module which promises to let one access processes in a platform agnostic way without any PID files involved - might be worth a look too.

**Comment by gtozzi** [comment]
The psutil module does not seem to do that, what method/function did you see?
There is a tendo.singleton module that aims to do that, but it only applies to any instance without option to discern between config paths.
Checking the command line path is not an option because some OS/variants mess up with it and, anyway, what if i invoke one instance with -psn and the other bymanually passing ~/.nagstamon as config folder? They both use the same config but have different command lines.
Placing a lock in the config folder does not seem a bad solution because the lock is config-related and the config folder needs to be writable anyway. "Nagstamon-crashed-but-PID-file-still-hanging-around-and-blocking-new-start" is virtually not a problem: a PID file is handled by writing your PID inside of it, so if the application crashes, when you restart it it's almost impossible that you will get the same pid again. Even if it happens (and it's an incredibly rare problem common to almost every application), the only think you have to do is try again and it will work.
Placing a lock to the folder is a more elegant solution but it requires an extra module and may be less robust.

**Comment by HenriWahl** [comment]
OK, sounds cool for me.
What would be the GUI part? Any necessary at all? Some checkbox like "allow several instances of me"?

**Comment by gtozzi** [comment]
There is probably no need for a gui part anymore, unless you want to put an option to allow running two instances on the same config folder. Does it make any sense? Maybe for many users sharing the same config through a network shared folder?

**Comment by gtozzi** [comment]
I've just realized that if you have the config in a network share, then you are running nagstamon on two different PCs and then have two different PIDs :)

**Comment by HenriWahl** [comment]
Phew... indeed.

**Comment by gtozzi** [comment]
I've added it to my current pull request, see b9a96621ce62b

**Comment by dgmorales** [comment]
In my case we have people using nagstamon in a LTSP environment, another case to be taken in consideration for this issue. Here each user uses different configs, but it could make sense for other people to share the config also.

Probably easy to fix.  Adding the username to the lockfile name or filtering by current username when checking for existent processes are good options I guess.

I also think it would be totally acceptable if this feature be optional (checkbox in UI), and didn't get every possible use case right. Maybe add a note in the tooltip or something like that. If it does not work for someone, just turn it off.

**Comment by HenriWahl** [comment]
Done.
