### ISSUE TITLE
v2.0 Acknowledgment fails

### ISSUE THREAD

**Issue by sronline** [HenriWahl/Nagstamon#192]
we observed that the acknowledgment sometimes fails. The reason is that nagstamon uses the "display_name" instead of "service_description":

> define service {
>          #NAGIOSQL_CONFIG_NAME           nrpe_sesam_DATEN3_Musik
>          host_name                       BUP-A
>          service_description             NRPE_SESAM_DATEN3_MUSIK
>          display_name                    SESAM_DATEN3_MUSIK
>          check_command                   check_nrpe!check_sesam_DATEN3_Musik
>          max_check_attempts              3
>          check_interval                  180
>          retry_interval                  10
>          check_period                    24x7
>          notification_interval           600
>          notification_period             24x7
>          notification_options            w,u,c,r
>          notifications_enabled           1
>          contact_groups                  admins
>          failure_prediction_enabled      1
>          register                        1
>  }

![nagstamon_problem3](https://cloud.githubusercontent.com/assets/17158346/13044757/39795d28-d3d0-11e5-94c7-7d3b860c34fd.PNG)

Using the display_name leads to a "Not authorized" error:
![nagstamon_problem1](https://cloud.githubusercontent.com/assets/17158346/13044695/cffb2a7a-d3cf-11e5-9f84-e72bb65d242b.PNG)

**Comment by HenriWahl** [comment]
This is Icinga, right?
If it fails sometimes I assume it does when display_name and service_description differ?

**Comment by sronline** [comment]
Icinga 1.8.4. Yes it fails when display_name and service_description differ

**Comment by HenriWahl** [comment]
Does this occur with other actions like "set downtime" too?

**Comment by HenriWahl** [comment]
Done with latest commit - please check if acknowledges now. The thing about setting downtime would be of interest too.

**Comment by minibbjd** [comment]
Tested with IcingaWeb2 and both acknowledge and downtime work fine for me.

**Comment by yasa1987** [comment]
This bug correction introduced another bug when using version 2.0.1 and Icinga 1.7.1 (currently in the Debian stable repository) :
`ERROR: 2017-05-29 11:01:14.586506 Netmon Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Icinga.py", line 256, in _get_status_JSON
KeyError: 'host_name'`

This is line 256 :
`self.new_hosts[host_name].real_name = s['host_name']`
20 lines upper 's' is always tested against 'host_name' key existence but not this time. 
To avoid the issue, I propose following correction:
`self.new_hosts[host_name].real_name = s['host_name'] if 'host_name' in s else host_name`

**Comment by HenriWahl** [comment]
Added your fix - can you check if it works for you now?

**Comment by yasa1987** [comment]
There is the same issue at line 291  :
`ERROR: 2017-07-21 09:32:50.392922 TVmon Traceback (most recent call last):
  File "C:\say\code\Nagstamon\Nagstamon\Servers\Icinga.py", line 291, in _get_status_JSON
    self.new_hosts[host_name].services[service_name].real_name = s['service_description']
KeyError: 'service_description'`

The point is that **service_description** key is not returned by Icinga 1.7.1 and your code did not check againts its existence. Here is the data contained in the variable **s** :
`{'host': 'ita-cmts02.catv', 'service': 'Cable6/1-upstream3 - SNR', 'status': 'WARNING', 'last_check': '2017-07-21 09:4
2:31', 'duration': '0d  0h 39m  0s', 'attempts': '5/5', 'is_flapping': True, 'in_scheduled_downtime': False, 'active_che
cks_enabled': True, 'passive_checks_enabled': True, 'notifications_enabled': True, 'has_been_acknowledged': False, 'host
_display_name': 'ita-cmts02.catv', 'service_display_name': 'Cable6/1-upstream3 - SNR', 'status_information': 'Le SNR est
 de 18.7dB pour la VR "Etrier 2"'}`

 I rewrote it in order to use **service_display_name** if **service_description** does not exist:
`self.new_hosts[host_name].services[service_name].real_name = s.get('service_description', s.get('service_display_name'))`

I used the **get** method on dictionaries because it's more reliable than directly addressing the key, especially when the key does not exist.

**Comment by HenriWahl** [comment]
I did not know the get() method but it looks pretty useful. I applied your fix in latest commit.
