### ISSUE TITLE
[feature-request] Thruk, toggle backend

### ISSUE THREAD

**Issue by riskersen** [HenriWahl/Nagstamon#219]
Hi all,

we're using Thruk as GUI for different Nagiose. In Thruk, you can toggle each Backend. 

It would be very nice to support this behavior in Nagstamon as well.

BR
Oliver

**Comment by HenriWahl** [comment]
Nagstamon takes what it gets from your monitoring server and does not have any idea about any backend. Thruk presents its data in its way which is evaluated by the Nagstamon Thruk module so the backends should not have any influence.

**Comment by riskersen** [comment]
So Thruk is not delivering the information from which Backend/Site the Alert is coming from?

**Comment by HenriWahl** [comment]
I think so and otherwise see no use in this information if it even would be sent - the client will be interested in the state information, not how it was retrieved. If you choose Thruk as monitor type in Nagstamon it should get the right info from your Thruk server.

**Comment by riskersen** [comment]
Lets imagine you're an administrator for several Nagios Systems of different Teams or Customers.

With Thruk you have a centralized overview of all Nagiose, but what if there are Nagiose you don't need to see everytime? In Thruk GUI, you see all configured backends/nagiose in the top bar which you can enable or disable. With that you'll get a better overview of what is happening for Nagiose where you actually need to do something on alerts.

When using nagstamon, its not possible. Either you have to configure aaall the Nagios GUIs from each server or you have to deal with a lot of information, which you don't need..


Do you get the point why i'm requesting something like that?

**Comment by HenriWahl** [comment]
Your problem might be solved with using several monitors in one Nagstamon instance - see settings first "Servers" tab. These you can enable/disable as needed. Another solution is running several instances of Nagstamon with different configurations.

Any other solution might be pretty much overkill as not that many people use Thruk and of them not all will have your requirement - anyway I doubt that Thruk shows the underlaying monitoring server.

If anybody will code a working solution I won't hesitate to look at it but I am not able to provide one.

**Comment by HenriWahl** [comment]
No real solution -> close

**Comment by fermino** [comment]
Hey :)

I am currently needing this for my workplace for the same reasons stated above. We have a unified, multi-backend thruk instance which centralizes status information from different backends. Each area has its own backend for which they maintain the configuration, but we also have a dedicated monitoring team that should have access to a centralized dashboard with all the alerts. 

I am already implementing this in nagstamon, the idea would be to have a filter in the configuration that corresponds to [this filter in thruk](https://www.thruk.org/documentation/rest.html#_backends-sites) so that all the people access the same thruk instance and they filter what they need to see. 

If I implement it, could it be accepted? Obviously it would need to be a proper implementation and not a hacked-together one :)
