### ISSUE TITLE
Feature request: Input box for Check_MK custom service/host view name.

### ISSUE THREAD

**Issue by z387-github** [HenriWahl/Nagstamon#255]
Hi,

Would it be possible to customize, maybe via an input box in the settings, the view names used by Nagstamon to poll Check_MK (nagstamon_hosts and nagstamon_svc)?

Those views can be customized in Check_MK with multiple filters (filters explicit to Check_MK like WATO folder for example) to get exactly what I need to be shown in Nagstamon.

Since I need to create multiple views for multiple teams at my company, the only way I get to do that as of now is to compile multiple versions of Nagstamon, and change within each one the following lines in Nagstamon/Nagstamon/Servers/Multisite.py :

```
84              'api_services':    self.monitor_url + 'view.py?view_name=nagstamon_svc&output_format=python&lang=&limit=hard',
86                                                   urllib.parse.urlencode({'start_url': 'view.py?view_name=nagstamon_svc'}),

90              'api_hosts':       self.monitor_url + 'view.py?view_name=nagstamon_hosts&output_format=python&lang=&limit=hard',
92                                                   urllib.parse.urlencode({'start_url': 'view.py?view_name=nagstamon_hosts'}),
```

Cheers,

**Comment by HenriWahl** [comment]
Isn't there an easier way to cut down the things your operators see by using groups directly in Check_MK?

**Comment by hailtojohnny** [comment]
That could be an option for some people, but it does not work for us since
some teams need to access the other teams alerts, but they do not want to
get the alerts at all time in their personal view.

Rather complicated to explain, but to get what we really want, we uses
multiple filters on the views that are proper to Check_MK (WATO Folder,
Host tags, etc.).  Another option would have been to customize the view
inside Nagstamon, but since those filters are proper to Check_MK, it would
be too troublesome to implement this.

Maybe my request is too precise, and would not be beneficial for anyone
else and not worth implementing...

**Comment by HenriWahl** [comment]
Please check latest testing version from https://nagstamon.ifw-dresden.de/download/#testing.
