### ISSUE TITLE
Nagstamon 2.0 Ack on 1 item ack's them all in Zabbix 2.2.2

### ISSUE THREAD

**Issue by waardd** [HenriWahl/Nagstamon#299]
When i acknowledge an alert in Nagstamon for a host it acknowledges all the events that are open in Zabbix.
So if I have 5 events and I acknowledge one with "Working on it", then all 5 get this acknowledgement.

**Comment by HenriWahl** [comment]
Very optimistic approach... well, seems to be worth a look. Might take a while because the Zabbix module is rather experimental but it is now on the todo list.

**Comment by HenriWahl** [comment]
Or isn't Zabbix 2.2.2 pretty outdated anyway? Maybe the problem is on the server?

**Comment by waardd** [comment]
Thank you for your reply.

I'm a fan of Zabbix so I hope it will become permanent item in Nagstamon.
Also a great fan of the Nagstamon tool :)

I will continue to test and report.



2016-09-01 8:34 GMT+02:00 Henri Wahl <notifications@github.com>:

**Comment by nono-gdv** [comment]
Hello, sorry I'm late replying.

I wrote (or at least heavily modified) the acknowledge code in the Zabbix back-end. I couldn't find a reliable way to identify a specific trigger, I'm not sure the Zabbix API allows it, at least not the way it is used in the Nagstamon back-end (not my own code in the beginning). I chose the optimistic approach to acknowledge all triggers with the same name as it works in my setup, but I know very well it is broken.

Maybe a complete rewrite of the Zabbix back-end would fix this issue, but I'm not sure I'm up to it and I don't have much time to contribute anyway. Or maybe the API has been improved since 2.2, but I don't have access to anything more recent.

So no real answer here, except "I know it's broken and I don't know how to fix it", sorry.

**Comment by HenriWahl** [comment]
Hi @nono-gdv @waardd ,
as I do not use Zabbix and have on experience with it I am not going to rewrite the Zabbix backend - aside the the fact there is some other stuff to do :-).
As Zabbix support is still tagged "experimental" this stuff that could happen...

**Comment by mprenditore** [comment]
I should have fixed the problem with my latest pull request.
@nono-gdv I fixed the api query to get the result ordered because seams that Zabbix only accept ASC/DESC and not asc/desc. The variable "triggerids" is also unsupported since Zabbxi 2.2 and now must be used "objectids".
Anyway, to ACK only the latest event of the specified trigger I added a "break" at the first event that is in OK status.

It seams work well for me, let me know if is the same for you.

**Comment by waardd** [comment]
Is this fix in the latest stable version (2.0.1) of nagstamon?

If not, can you tell a noob how to use this latest update?

2016-10-24 15:42 GMT+02:00 Stefano Stella <notifications@github.com>:

**Comment by mprenditore** [comment]
@waardd not yet, it will be available on 2.1
On which platform are you? Windows, Mac or Linux?
You should clone the git repository and test it launching the file "nagstamon.py" (how depends on your platform)
if work, you should execute via terminal that command from the directory of Nagstamon "python3 setup.py install" to install it.
After that you will be able to launch it as you do with the installed one.

Let me know if you need more help

**Comment by waardd** [comment]
I'm using nagstamon on Windows (7 and 10)

2016-10-25 19:50 GMT+00:00 Stefano Stella <notifications@github.com>:

**Comment by HenriWahl** [comment]
See https://nagstamon.ifw-dresden.de/docs/requirements/ to get a working run-from-source environment even on Windows.

**Comment by HenriWahl** [comment]
Seems fixed.

**Comment by HenriWahl** [comment]
@waardd find binaries at https://nagstamon.ifw-dresden.de/download/#unstable
