### ISSUE TITLE
Problem with Centreon 2.8

### ISSUE THREAD

**Issue by Ale171** [HenriWahl/Nagstamon#359]
The URL http: //IP/Centreon doesn't works and displays Monitoring URL invalid. 
What URL should be set ?

Thanks,

**Comment by fildar** [comment]
I am working with Ale171.
To give the solution to those who would have the same issue:
After Centreon has been upgraded to the 2.8.3 version, Nagstamon could not connect to our monitor and shows : "Monitor URL not valid".
I installed the last unstable 2.1 version (2.1-20161129).
Nagstamon is now able to connect to the monitor but doesn't display CRITICAL or UNKNOWN alerts.
Our admin account language is still in fr_FR.UTF8 since the upgrade (the language pack has not been replaced).
I had a look to [this post](https://github.com/HenriWahl/Nagstamon/issues/344) and modified our admin account language to en_US as recommended by @BenoitPoulet. And it worked like a charm.
We just need to update the FR language pack as he recommends and see if we can put the language of our admin account back in FR ;)

**Comment by BenoitPoulet** [comment]
Hello,

The lastest unstable build is required for Centreon 2.8 as the last stable only support Centreon 2.7.

But if the user configured in Nagstamon has fr_FR.UTF-8 as language in Centreon, it's not enough.

You will need the patch #356 , checkout the Github tree or wait until @HenriWahl build another unstable build.
Or you can set language in en_US as a temporary workaround.

**Comment by fildar** [comment]
Hi @BenoitPoulet,
I was writing to you in the post #344 :)
@Ale171 updated the FR language pack but the issue remains.
We are going to try the patch you described in #356 
As we would want to keep the admin user with a fr_FR language, we could create another user with en_US and use it in Nagstamon?

**Comment by BenoitPoulet** [comment]
Yes of course, you can use a specific user for Nastamon.

**Comment by fildar** [comment]
Works fine but it seems that the user needs to be Admin in Centreon to be able to acknowledge

**Comment by fildar** [comment]
My bad, my colleagues just told me the right to acknowledge can be given and that there is no need to be Admin.
Many thanks for your support!

**Comment by BenoitPoulet** [comment]
i think  we can close this issue.

**Comment by HenriWahl** [comment]
Thus it shall be...
