### ISSUE TITLE
Feature request: Local acknowledge / temporary filter

### ISSUE THREAD

**Issue by cverbiest** [HenriWahl/Nagstamon#364]
I'd like to be able to acknowledge / hide / filter out  an issue in the nagstamon client without acknowledging on server level.

Sometimes issues I cannot handle remain open for a long time. 
I do not want to acknowledge them, this would remove them from other nagstamon displays, 
I just want to hide them from my display as if they had been acknowledged.

I do not want to filter out them permanently,

**Comment by BenoitPoulet** [comment]
There are filters with regexp on Nagstamon : Settings -> Filters

**Comment by mkrsn** [comment]
@Devs: Please don't implement such dirty workarounds. This would bring user to handle the monitoring incorrectly.

Basically Host-/Service-Problems should be fixed instead of ignoring it. So if there is a Check critical -> Fix the Host/Service. If the "critical" is not critical -> fix the Monitoring

**Comment by HenriWahl** [comment]
I do not consider this a good idea as you get incoherent views of the current state.
