### ISSUE TITLE
Nagstamon 2.0.1 crashes on ack of Problem

### ISSUE THREAD

**Issue by mg-p14** [HenriWahl/Nagstamon#390]
Hi,
my Nagstamon crashes when I try to a acknowledge a problem.
OS: macOS Sierra
Nagstamon 2.0.1
Monitortype: Zabbix (latest 3.2)

Is there anything I can provide you, so that you can take a look into this?
Here is the crash log:
[nagstamon_2017-06-07-162611_Mathiass-MacBook-Pro.crash.zip](https://github.com/HenriWahl/Nagstamon/files/1058325/nagstamon_2017-06-07-162611_Mathiass-MacBook-Pro.crash.zip)

Maybe it is useful.

If there are any further questions just let me know.

Regards from Darmstadt Germany

Mathias

**Comment by mprenditore** [comment]
Hello,
I'm aware of the problem and I'm working on a solution, unfortunately I don't have a lot of free time lately to work on it.

I'll hope that this weekend I can work on it to finally solve it, the main problem is that the old system in Nagstamon to show triggers didn't worked well in case there were more than one trigger with the same app name on Zabbix and due to my new implementation of it I introduced another bug on the ack system. I'm sorry about that but I thought it was better to show all the problems and after working on the ack system even because it wasn't working with previous implementation.

I'll keep you updated.
S

**Comment by mg-p14** [comment]
Hello,
thanks for the update.
If you need any futher testing just let me know.
All the Best
Mathias

**Comment by HenriWahl** [comment]
Please check latest testing version from https://nagstamon.ifw-dresden.de/download/#testing.
