### ISSUE TITLE
v3.x MacOS version limit/bug?

### ISSUE THREAD

**Issue by pbrunnen** [HenriWahl/Nagstamon#449]
I believe this may be a bug as I didn't see anything in the release notes about there being a limitation on MacOS versions for the new 3.x train. I'm unable to launch any of the 3.x versions on my Mac; my system is a non-retina Macbook Pro on 10.11.6.
v2.0.1 is working well.  3.x versions all exit and do not log anything very useful.
```
Nagstamon[2275]: ApplePersistence=YES
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000014.Nagstamon[2275]): Service exited with abnormal code: 255
```

**Comment by HenriWahl** [comment]
Nagstamon for macOS was built on 10.12, apparently there is a dependency. I will see if I find a 10.11 to build - or you upgrade your machine? :-)

**Comment by pbrunnen** [comment]
Hello HenriWahl,
Ah, Ok. No need to rebuild for 10.11... You may just want to note it on the download page.
Thank you.  :)

**Comment by LucaNonato** [comment]
> I will see if I find a 10.11 to build

I'm using 10.11 - and i can run Nagstamon from the Python source - but having a standalone app would be easier: if you have a Xcode project or something i'll be glad to help.

Luca

**Comment by HenriWahl** [comment]
Happy New Year.... there is no Xcode project file but if you are able tu run it from source you might as wll run the included build script after you fulfilled the requirements as seen on https://nagstamon.ifw-dresden.de/docs/requirements/.

**Comment by LucaNonato** [comment]
Happy new year to all of you, too!

I tried building it via "python3 setup.py install", but i'm getting the following error:
`Traceback (most recent call last):`
`  File "setup.py", line 38, in <module>`
`    VERSION = AppInfo.VERSION.replace('-', '.') + '.' + DIST + DIST_VERSION`
`NameError: name 'DIST' is not defined`

Looking at "setup.py" this is part of:
`NAME = AppInfo.NAME`
`OS = platform.system()`
`# make name lowercase for Linux/Unix`
`if OS not in [\'Windows\', \'Darwin\']:`
`    DIST, DIST_VERSION, DIST_NAME = platform.dist()`
`    NAME = NAME.lower()`
`VERSION = AppInfo.VERSION.replace('-', '.') + '.' + DIST + DIST_VERSION`

Is it just me or pasting multiple lines of code in a single quote block doesn't work properly?. I had to put the "`" on each line otherwise the CR was not properly shown.

P.S.: Yes, i have to explicitly use "python3", also when directly running it, otherwise my Mac OS tries to use python2.

**Comment by HenriWahl** [comment]
Where did you get your Python3 from? From Homebrew as in the indicated manual?

**Comment by HenriWahl** [comment]
Anyway just run the build script, no setup.py.

**Comment by HenriWahl** [comment]
Find it in the build/ directory.

**Comment by LucaNonato** [comment]
> Where did you get your Python3 from? From Homebrew as in the indicated manual?

Yes.

> Anyway just run the build script, no setup.py

Ok, this worked fine. I can send you the DMG file, if you want to add it to the download page for other users using 10.11...

**Comment by HenriWahl** [comment]
OK, can you upload it to https://seafile.ifw-dresden.de/u/d/b97f88eb5a1449c3b2fb/?

**Comment by LucaNonato** [comment]
File uploaded!

**Comment by HenriWahl** [comment]
Thanks. I guess it is not infected by any bad stuff...

**Comment by LucaNonato** [comment]
Not that i know of... :)
By the way, i checked it with ClamXav before sending it, to be sure, and it was clean.
