### ISSUE TITLE
Empty host XML result

### ISSUE THREAD

**Issue by lorrainezo** [HenriWahl/Nagstamon#451]
Hello,

Since installation of Nagstamon-3.0.2-win64_setup.exe on win8.1 x64, I have sometime this error "Empty host XML result" after I acknowledge one alarm on Centreon 2.7.11 (right-click on one alarm > Acknowledge > OK)

After this error appear, I need to restart Nagstamon in order to check work again.

I haven't DebugMode activate, so next time this problem appear, I will post it.

Laurent

**Comment by lorrainezo** [comment]
Hello,

Again this bug, now I'm on Centreon 2.8.12.
In attachment is my logfile. Error appear today 19/10 around 15h48 after acknowledege this alert "SVIE-INIW-SQL19;App-DB-MSSQL-Database-Used"

[nagstamon_302 - Copie.log](https://github.com/HenriWahl/Nagstamon/files/1398626/nagstamon_302.-.Copie.log)

**Comment by BenoitPoulet** [comment]
Hello,

Can you tell me if this PB happens **every times** you do an Ack ?

After your Ack on "SVIE-INIW-SQL19;App-DB-MSSQL-Database-Used", there were still Services or Hosts that was not under downtimes or acknowledged ?

**Comment by lorrainezo** [comment]
Hello Benoit,

This problem don't appear each time I acknowledge.

And yes, after this acknowledge, there are 6 other services without Ack or Down Time 

Below, it's an old screen shoot of this problem :
![image](https://user-images.githubusercontent.com/16103827/31820596-4d3ceafe-b5a2-11e7-8534-850b18b165bd.png)

**Comment by Mario-Hofstaetter** [comment]
We too have this issue on `nagstamon 3.0.2` connected to `Centreon 2.7.0`. It does not always appear, it seems to happen more frequently when using the manual "Refresh" Button after acknowledging or rechecking an alert. We will provide logs when it happens again.

**Comment by BenoitPoulet** [comment]
Hello,

I would like to know if the account you are using in you Nagstamon is configured only in one Nagstamon install or on several.

**Comment by BenoitPoulet** [comment]
@Mario-Hofstaetter 
Ok that's the origin of the PB; different sessions with the same user. 
We saw the same behavior (random session lost) with guys who had several google chrome browser open with the same user logged in.

I don't know if it's a good thing to do but in my point of view, no.

@lorrainezo And you ? Can you tell us if you use the same user on several install ?

Anyway i did a check at the start of the refresh of services & hosts; if the sessions is not ok; i ask for a new session. I think it will fix the refresh problem; but the problem can appear again elsewhere.

The problem is that i can't check the fix quickly on an 2.7 install as i don't have it anymore and i'm very busy at this moment.

If someone can provide me a test account on a non-production centreon i can check it by myself. Or if you can run Nagstamon from the sources you can checkout my github fork and give me feedback.

**Comment by lorrainezo** [comment]
Hello Benoit,

My account is used only on 1 Nagstamon. But sometimes I'm connected to Centreon 2.8.12 with Firefox, so I don't know if it's same problem than use same login on more than 1 Nagstamon.
Next time problem appear, I will notice if I'm connected to centreon with Firefox.

**Comment by lorrainezo** [comment]
Hello Benoit,
Yesterday I encounter same problem and I wasn't connected to Centreon 2.8 with Firefox.
After this error empty XML Host, I have launch a Recheck All and Refresh.
I attach the log file.

[nagstamon_302 - bug 25-10.log](https://github.com/HenriWahl/Nagstamon/files/1417488/nagstamon_302.-.bug.25-10.log)
log file,

**Comment by BenoitPoulet** [comment]
Attempt to fix in push request #455 

To test it you will need to run Nagstamon from the source of wait the next unstable binary build
