### ISSUE TITLE
[Need infos] Centreon class dev

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#463]
Hello,

@HenriWahl and others involved in the project,

**I'm thinking about adding support for the new Centreon REST API in Nagstamon.**

But all is changing with this API, and it's supported only in Centreon greater than 2.8.14 (Latest stable version is 2.8.15)

In your point on view, what is the best method ?
  - Put a lot of "if" in the class to implement this
  - Do a big "if API" at the beginning of the class and do 2 big section
 - Create another class

**Another part is the version support**.
Centreon is moving a lot, with many changes between versions (urls are changing, parameters, session management, ...)
To not rewrite all the code for each version i do a lot of "if version", but with the live of the code , the code become big, and i can't test it against the old versions.
What to do with the old (untested) code ? How many version we must maintain ?

For version support, better to do auto-detection ? or ask the user the version of the product ?

Regards.

**Comment by HenriWahl** [comment]
I think a big "if API" at the beginning will make it clearer for anyone working with the code instead of many small "if"-blocks. 
When the old versions worked with the older releases of Centreon I think it is OK if they do not get much maintenance as Centreon itself hopefully would not change their API back in time. So if you keep up with the current releases of Centreon you still have a lot to do. :-)
Asking the user might cause more confusion on the user side so I would prefer auto-detection as you do it now.

**Comment by BenoitPoulet** [comment]
Ok, thanks for the ideas.

Do you think it would be possible to add a checkbox "use API" in the "Show more options" block ?
Because in Centreon the API rights are optional and must be enabled user per user.

But if the user choose this the checkbox "Use auto login" must be cleared, and unavailable.

Don't do anything now, i just want to know if it's possible.

**Comment by HenriWahl** [comment]
Absolutely a good idea - might even help to get users to test if API works.
If API is enabled server-side for a user she/he only can use API?

**Comment by BenoitPoulet** [comment]
No, if enabled, the user can use both methods

**Comment by HenriWahl** [comment]
Let me know if you need some GUI support.
