### ISSUE TITLE
Nagestamon 3.2.1 not working with Zabbix 4

### ISSUE THREAD

**Issue by ortizleo** [HenriWahl/Nagstamon#535]
Hello.
Nagstamon with zabbix 4 show all hosts as UNREACHABLE. 
Image attached.
![image](https://user-images.githubusercontent.com/17042298/50961618-4e7a9700-14af-11e9-8e53-25469c7a7e9c.png)

**Comment by zetheroo** [comment]
We also have this issue with the same version of Zabbix and Nagstamon. Zabbix hosts that are not using the Zabbix Agent are shown in Nagstamon as 'Unreachable'.

**Comment by Daznis** [comment]
I think it's more of an issue with zabbix in general and not related to v4. I have a 2.4 version nad have a load of hosts unreachable. All of the hosts in my case are either down/unreachable or in maintenance mode. And having them filtered out doesn't help at all. My suspicion is that filtering system is not working properly right now.

**Comment by zetheroo** [comment]
Are the hosts showing up in Nagstamon as unreachable using the Zabbix Agent?

**Comment by noonedeadpunk** [comment]
Do you have None Availability for these hosts, like on the screenshot?
![screenshot_20190212_205558](https://user-images.githubusercontent.com/22073608/52660898-652a6880-2f09-11e9-950e-67aaa7aa837d.png)

If yes, than probably the problem is here: https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Zabbix.py#L179-L182

I think, that we shouldn't suggest host as unreachable only if it has no UP agents - it's pretty normal usecase for zabbix not to attach host to any agent (zabbix/snmp/ipmi/jmx) - for example, if we would like just to check ping to the host from zabbix server or we don't have access to this host, but still want to check it's accessibility. From the other side, it's possible to filter UNREACHABLE for zabbix, unless you're using it with nagios, which is the case for me. So I'm not able to filter out UNREACHABLE, as for nagios UNREACHABLE is pretty critical and usual situation.

So I think, that the good option will be somehow to re-think meaning on unreachable state for zabbix, as missing of all agents doesn't mean, that smth is wrong with zabbix host itself.

**Comment by hyperman1** [comment]
We have this problem both on zabbix 4.0 and 3.4.

noonedeadpunk's  analysis is correct, and in fact the previous version of nagstamon was like this:

                # if host is disabled on server safely ignore it
                if host['available'] != '0':

A workaround is to filter out all down hosts.

Even so, I propose to simply remove the lines of code pointed at by noonedeadpunk, and consider the 4 zeroes situation as a host without problems

**Comment by noonedeadpunk** [comment]
@HenriWahl can you please look into this case?

**Comment by HenriWahl** [comment]
@noonedeadpunk can you please test with latest testing relase from https://nagstamon.ifw-dresden.de/download/#testing ?

**Comment by noonedeadpunk** [comment]
@HenriWahl The point is not that nagstamon is not working with zabbix4, but that since some point it raises UNREACHABLE for zabbix hosts, that has no active agents (topic is a bit irrelevant). For zabbix having no agents is pretty ok, as you may want just to check ping from zabbix server - all these hosts will be shown as UNREACHABLE, which is not essentially the case.

So my suggestion was to somehow adopt UNREACHABLE state for zabbix hosts. Or simply remove mentioned lines like @hyperman1 offers.

PS: 3.3-20190326 doesn't do the trick

**Comment by HenriWahl** [comment]
Sorry for the confusion... binaries with your proposed change shall be available within the next minutes at https://nagstamon.ifw-dresden.de/files/incoming/ - please test them.

**Comment by hyperman1** [comment]
Your test version Nagstamon-3.3-20190415-win64   fixes this.  Thanks!

**Comment by noonedeadpunk** [comment]
+1 nagstamon_3.3-20190415_all.deb solves problem for me.
