### ISSUE TITLE
Virustotal: Virus found

### ISSUE THREAD

**Issue by ihe-nu** [HenriWahl/Nagstamon#786]
Hi,

in all four Windows-Versions Virustotal shows some odds:

Nagstamon-3.8.0-win32.zip - 3/61 https://www.virustotal.com/gui/file/61f19896e244e42b44b096181c96f84fab0d019cfb3e89c1b5ccacfd8e1af8cd
Nagstamon-3.8.0-win32_setup.exe - 2/65 https://www.virustotal.com/gui/file/707d37b60c7212468d9f5d8914a2605340e71f68bdc6978f87bc8a6d37083784
Nagstamon-3.8.0-win64.zip - 11/56 https://www.virustotal.com/gui/file/069e3bdd6c892c52e27cc39b265a5051b64f93af9ba7e78af7038454cac8f8d8
Nagstamon-3.8.0-win64_setup.exe 2/62 -  https://www.virustotal.com/gui/file/f24043f8618871a6ba37251436ea23768cbfb489eafac5e415cdb86d8677f29d

This was also with 3.6.0 the case:
Nagstamon-3.6.0-win32.zip 23/61 - https://www.virustotal.com/gui/file/819ca5d6228bee1c482791503cbc629f8bddc3997f038545ad247c0c4cb30d4a

Is this known behavior?

cheers,
ihe

**Comment by HenriWahl** [comment]
Yes, I am sorry to say this is known behavior. The used PyInstaller for creating these binaries has the problem since years to be recognized as malware even if it isn't. The only chance is to ask the vendors to whitelist Nagstamon. This procedure differs from vendor to vendor. For some this already happened. If there is one blocking you locally please just try to find out how to report a false positive and file a report there.
