### ISSUE TITLE
Hide Mac App from Dock

### ISSUE THREAD

**Issue by christiangierschner** [HenriWahl/Nagstamon#873]
Hello,

if I build Nagstamon with these additional lines in Nagstamon.py, it is started in the menubar, and just menubar

```
import AppKit
info = AppKit.NSBundle.mainBundle().infoDictionary()
info["LSBackgroundOnly"] = "1"
```
I used pyobjc for AppKit

Issues:
 - Nagstamon settings window won't show up in focus in foreground but behind another window
 - Textfields are not! editable, keystrokes go to the last active app 

Wishlist:
 - /Applications Link/Alias in DMG file for dragging app to Applications https://www.pythonguis.com/tutorials/packaging-pyqt5-applications-pyinstaller-macos-dmg/

Thanks :)

**Comment by Jay2k1** [comment]
I hate to be that guy, but I'd prefer if Nagstamon keeps the Dock icon, since i'm using it in windowed mode on one of my screens, sometimes I move another window over it and then I can't alt-tab (or Dock-click) to look at Nagstamon (and there's no "systray"/info bar icon in this case either). And apparently [I'm not alone](https://github.com/HenriWahl/Nagstamon/issues/333#issuecomment-258989135) with this preference.

I'd say it should either only be hidden when you use the statusbar (and maybe fullscreen?) mode and not a regular window, or it should be a setting, which you (Henri) seem to have wanted too, looking at https://github.com/HenriWahl/Nagstamon/issues/333#issuecomment-256879017.

**Comment by HenriWahl** [comment]
Yes, this is work in progress. I plan to make it an option but did not find the time to implement it.
The problem is that this is only a semi-on-off option and will result in a rather hackish solution, but I almost got it.

**Comment by HenriWahl** [comment]
@Jay2k1 please check latest testing release which shows an option to hide the dock icon when choosing systray. Default is the previous behaviour of showing dock icon.

**Comment by Jay2k1** [comment]
Yes, that seems to work well!

I tried compiling latest master myself, but when running the app, I now get
```
Traceback (most recent call last):
  File "nagstamon.py", line 42, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "Nagstamon/QUI/__init__.py", line 99, in <module>
ModuleNotFoundError: No module named 'AppKit'
```
when trying to start.

Does `build/requirements/macos.txt` need an update for this maybe?

**Comment by HenriWahl** [comment]
Actually https://github.com/HenriWahl/Nagstamon/blob/master/build/requirements/macos.txt#L7 should bring the AppKit module.

**Comment by HenriWahl** [comment]
@Jay2k1  please try latest release https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon.3.11-20230227.dmg which improved the no-icon-on-dock-behavior by allowing keyboard focus in dialogs when hidden.

**Comment by Jay2k1** [comment]
I'm not sure what exactly you want me to test, can you be more specific? I can confirm that when running in systray mode and have the dock icon hidden, and then open the settings, I can use tab to switch between the `OK` and `Cancel` buttons. Also, running in windowed mode, the dock icon is present as expected.

**Comment by Jay2k1** [comment]
Hm, after my tests, I went back to windowed mode. Whenever I enter the settings now and click OK, the window disappears - and there's no dock nor statusbar/tray icon.
